// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// 引擎配置消息（替代之前的 Map<String, dynamic>）
///
/// Generated class from Pigeon that represents data sent in messages.
struct EngineConfigMessage {
  /// 鉴权 — 必需
  var appId: String
  var appKey: String
  var appToken: String
  var resourceId: String
  var uid: String
  var dialogAddress: String
  var dialogUri: String
  /// 引擎基础
  var debugPath: String? = nil
  var logLevel: String
  /// AEC 回声消除
  var enableAec: Bool
  var aecModelPath: String? = nil
  /// 录音机
  var recorderType: String
  var recorderPath: String? = nil
  var enableRecorderAudioCallback: Bool
  /// 播放器
  var enablePlayer: Bool
  var enablePlayerAudioCallback: Bool
  var enableDecoderAudioCallback: Bool
  var playerPath: String? = nil
  /// 工作模式（null = 不设置，使用 SDK 默认值）
  var dialogWorkMode: Int64? = nil
  /// 重采样
  var enableResampler: Bool
  var customSampleRate: Int64? = nil
  var customChannel: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EngineConfigMessage? {
    let appId = pigeonVar_list[0] as! String
    let appKey = pigeonVar_list[1] as! String
    let appToken = pigeonVar_list[2] as! String
    let resourceId = pigeonVar_list[3] as! String
    let uid = pigeonVar_list[4] as! String
    let dialogAddress = pigeonVar_list[5] as! String
    let dialogUri = pigeonVar_list[6] as! String
    let debugPath: String? = nilOrValue(pigeonVar_list[7])
    let logLevel = pigeonVar_list[8] as! String
    let enableAec = pigeonVar_list[9] as! Bool
    let aecModelPath: String? = nilOrValue(pigeonVar_list[10])
    let recorderType = pigeonVar_list[11] as! String
    let recorderPath: String? = nilOrValue(pigeonVar_list[12])
    let enableRecorderAudioCallback = pigeonVar_list[13] as! Bool
    let enablePlayer = pigeonVar_list[14] as! Bool
    let enablePlayerAudioCallback = pigeonVar_list[15] as! Bool
    let enableDecoderAudioCallback = pigeonVar_list[16] as! Bool
    let playerPath: String? = nilOrValue(pigeonVar_list[17])
    let dialogWorkMode: Int64? = nilOrValue(pigeonVar_list[18])
    let enableResampler = pigeonVar_list[19] as! Bool
    let customSampleRate: Int64? = nilOrValue(pigeonVar_list[20])
    let customChannel: Int64? = nilOrValue(pigeonVar_list[21])

    return EngineConfigMessage(
      appId: appId,
      appKey: appKey,
      appToken: appToken,
      resourceId: resourceId,
      uid: uid,
      dialogAddress: dialogAddress,
      dialogUri: dialogUri,
      debugPath: debugPath,
      logLevel: logLevel,
      enableAec: enableAec,
      aecModelPath: aecModelPath,
      recorderType: recorderType,
      recorderPath: recorderPath,
      enableRecorderAudioCallback: enableRecorderAudioCallback,
      enablePlayer: enablePlayer,
      enablePlayerAudioCallback: enablePlayerAudioCallback,
      enableDecoderAudioCallback: enableDecoderAudioCallback,
      playerPath: playerPath,
      dialogWorkMode: dialogWorkMode,
      enableResampler: enableResampler,
      customSampleRate: customSampleRate,
      customChannel: customChannel
    )
  }
  func toList() -> [Any?] {
    return [
      appId,
      appKey,
      appToken,
      resourceId,
      uid,
      dialogAddress,
      dialogUri,
      debugPath,
      logLevel,
      enableAec,
      aecModelPath,
      recorderType,
      recorderPath,
      enableRecorderAudioCallback,
      enablePlayer,
      enablePlayerAudioCallback,
      enableDecoderAudioCallback,
      playerPath,
      dialogWorkMode,
      enableResampler,
      customSampleRate,
      customChannel,
    ]
  }
}

/// 指令请求
///
/// Generated class from Pigeon that represents data sent in messages.
struct DirectiveRequest {
  /// 指令名称，如 "DIRECTIVE_START_ENGINE"
  var directive: String
  /// 可选 JSON 参数
  var data: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DirectiveRequest? {
    let directive = pigeonVar_list[0] as! String
    let data: String? = nilOrValue(pigeonVar_list[1])

    return DirectiveRequest(
      directive: directive,
      data: data
    )
  }
  func toList() -> [Any?] {
    return [
      directive,
      data,
    ]
  }
}

/// 引擎事件消息（Native -> Dart）
///
/// Generated class from Pigeon that represents data sent in messages.
struct EngineEventMessage {
  /// 事件类型，如 "MESSAGE_TYPE_DIALOG_ASR_RESPONSE"
  var type: String
  /// 文本数据
  var text: String? = nil
  /// 二进制音频数据
  var audio: FlutterStandardTypedData? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EngineEventMessage? {
    let type = pigeonVar_list[0] as! String
    let text: String? = nilOrValue(pigeonVar_list[1])
    let audio: FlutterStandardTypedData? = nilOrValue(pigeonVar_list[2])

    return EngineEventMessage(
      type: type,
      text: text,
      audio: audio
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      text,
      audio,
    ]
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return EngineConfigMessage.fromList(self.readValue() as! [Any?])
    case 130:
      return DirectiveRequest.fromList(self.readValue() as! [Any?])
    case 131:
      return EngineEventMessage.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? EngineConfigMessage {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? DirectiveRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? EngineEventMessage {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DoubaoVoiceHostApi {
  /// 准备环境（App 生命周期内仅一次）
  func prepareEnvironment() throws -> Bool
  /// 创建引擎实例
  func createEngine() throws
  /// 批量配置引擎参数
  func configure(config: EngineConfigMessage) throws
  /// 设置字符串参数
  func setOptionString(key: String, value: String) throws
  /// 设置布尔参数
  func setOptionBool(key: String, value: Bool) throws
  /// 设置整数参数
  func setOptionInt(key: String, value: Int64) throws
  /// 初始化引擎，返回错误码（0 = 成功）
  func initEngine() throws -> Int64
  /// 发送指令
  func sendDirective(request: DirectiveRequest) throws
  /// 传入 PCM 音频数据，返回错误码
  func feedAudio(buffer: FlutterStandardTypedData) throws -> Int64
  /// 停止引擎（异步执行，避免回调线程死锁）
  func stopEngine(completion: @escaping (Result<Void, Error>) -> Void)
  /// 销毁引擎（异步执行）
  func destroyEngine(completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DoubaoVoiceHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `DoubaoVoiceHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DoubaoVoiceHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// 准备环境（App 生命周期内仅一次）
    let prepareEnvironmentChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.prepareEnvironment\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      prepareEnvironmentChannel.setMessageHandler { _, reply in
        do {
          let result = try api.prepareEnvironment()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      prepareEnvironmentChannel.setMessageHandler(nil)
    }
    /// 创建引擎实例
    let createEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.createEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      createEngineChannel.setMessageHandler { _, reply in
        do {
          try api.createEngine()
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      createEngineChannel.setMessageHandler(nil)
    }
    /// 批量配置引擎参数
    let configureChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.configure\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      configureChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let configArg = args[0] as! EngineConfigMessage
        do {
          try api.configure(config: configArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      configureChannel.setMessageHandler(nil)
    }
    /// 设置字符串参数
    let setOptionStringChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionString\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOptionStringChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! String
        do {
          try api.setOptionString(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOptionStringChannel.setMessageHandler(nil)
    }
    /// 设置布尔参数
    let setOptionBoolChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionBool\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOptionBoolChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Bool
        do {
          try api.setOptionBool(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOptionBoolChannel.setMessageHandler(nil)
    }
    /// 设置整数参数
    let setOptionIntChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionInt\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setOptionIntChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let keyArg = args[0] as! String
        let valueArg = args[1] as! Int64
        do {
          try api.setOptionInt(key: keyArg, value: valueArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      setOptionIntChannel.setMessageHandler(nil)
    }
    /// 初始化引擎，返回错误码（0 = 成功）
    let initEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.initEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      initEngineChannel.setMessageHandler { _, reply in
        do {
          let result = try api.initEngine()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      initEngineChannel.setMessageHandler(nil)
    }
    /// 发送指令
    let sendDirectiveChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.sendDirective\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendDirectiveChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! DirectiveRequest
        do {
          try api.sendDirective(request: requestArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      sendDirectiveChannel.setMessageHandler(nil)
    }
    /// 传入 PCM 音频数据，返回错误码
    let feedAudioChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.feedAudio\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      feedAudioChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let bufferArg = args[0] as! FlutterStandardTypedData
        do {
          let result = try api.feedAudio(buffer: bufferArg)
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      feedAudioChannel.setMessageHandler(nil)
    }
    /// 停止引擎（异步执行，避免回调线程死锁）
    let stopEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.stopEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      stopEngineChannel.setMessageHandler { _, reply in
        api.stopEngine { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      stopEngineChannel.setMessageHandler(nil)
    }
    /// 销毁引擎（异步执行）
    let destroyEngineChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.destroyEngine\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      destroyEngineChannel.setMessageHandler { _, reply in
        api.destroyEngine { result in
          switch result {
          case .success:
            reply(wrapResult(nil))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      destroyEngineChannel.setMessageHandler(nil)
    }
  }
}
/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DoubaoVoiceFlutterApiProtocol {
  /// 引擎事件回调
  func onEngineEvent(event eventArg: EngineEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class DoubaoVoiceFlutterApi: DoubaoVoiceFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// 引擎事件回调
  func onEngineEvent(event eventArg: EngineEventMessage, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceFlutterApi.onEngineEvent\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(Void()))
      }
    }
  }
}
