// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import, no_leading_underscores_for_local_identifiers

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

PlatformException _createConnectionError(String channelName) {
  return PlatformException(
    code: 'channel-error',
    message: 'Unable to establish connection on channel: "$channelName".',
  );
}

List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}

/// 引擎配置消息（替代之前的 Map<String, dynamic>）
class EngineConfigMessage {
  EngineConfigMessage({
    required this.appId,
    required this.appKey,
    required this.appToken,
    required this.resourceId,
    required this.uid,
    required this.dialogAddress,
    required this.dialogUri,
    this.debugPath,
    required this.logLevel,
    required this.enableAec,
    this.aecModelPath,
    required this.recorderType,
    this.recorderPath,
    required this.enableRecorderAudioCallback,
    required this.enablePlayer,
    required this.enablePlayerAudioCallback,
    required this.enableDecoderAudioCallback,
    this.playerPath,
    this.dialogWorkMode,
    required this.enableResampler,
    this.customSampleRate,
    this.customChannel,
  });

  /// 鉴权 — 必需
  String appId;

  String appKey;

  String appToken;

  String resourceId;

  String uid;

  String dialogAddress;

  String dialogUri;

  /// 引擎基础
  String? debugPath;

  String logLevel;

  /// AEC 回声消除
  bool enableAec;

  String? aecModelPath;

  /// 录音机
  String recorderType;

  String? recorderPath;

  bool enableRecorderAudioCallback;

  /// 播放器
  bool enablePlayer;

  bool enablePlayerAudioCallback;

  bool enableDecoderAudioCallback;

  String? playerPath;

  /// 工作模式（null = 不设置，使用 SDK 默认值）
  int? dialogWorkMode;

  /// 重采样
  bool enableResampler;

  int? customSampleRate;

  int? customChannel;

  Object encode() {
    return <Object?>[
      appId,
      appKey,
      appToken,
      resourceId,
      uid,
      dialogAddress,
      dialogUri,
      debugPath,
      logLevel,
      enableAec,
      aecModelPath,
      recorderType,
      recorderPath,
      enableRecorderAudioCallback,
      enablePlayer,
      enablePlayerAudioCallback,
      enableDecoderAudioCallback,
      playerPath,
      dialogWorkMode,
      enableResampler,
      customSampleRate,
      customChannel,
    ];
  }

  static EngineConfigMessage decode(Object result) {
    result as List<Object?>;
    return EngineConfigMessage(
      appId: result[0]! as String,
      appKey: result[1]! as String,
      appToken: result[2]! as String,
      resourceId: result[3]! as String,
      uid: result[4]! as String,
      dialogAddress: result[5]! as String,
      dialogUri: result[6]! as String,
      debugPath: result[7] as String?,
      logLevel: result[8]! as String,
      enableAec: result[9]! as bool,
      aecModelPath: result[10] as String?,
      recorderType: result[11]! as String,
      recorderPath: result[12] as String?,
      enableRecorderAudioCallback: result[13]! as bool,
      enablePlayer: result[14]! as bool,
      enablePlayerAudioCallback: result[15]! as bool,
      enableDecoderAudioCallback: result[16]! as bool,
      playerPath: result[17] as String?,
      dialogWorkMode: result[18] as int?,
      enableResampler: result[19]! as bool,
      customSampleRate: result[20] as int?,
      customChannel: result[21] as int?,
    );
  }
}

/// 指令请求
class DirectiveRequest {
  DirectiveRequest({
    required this.directive,
    this.data,
  });

  /// 指令名称，如 "DIRECTIVE_START_ENGINE"
  String directive;

  /// 可选 JSON 参数
  String? data;

  Object encode() {
    return <Object?>[
      directive,
      data,
    ];
  }

  static DirectiveRequest decode(Object result) {
    result as List<Object?>;
    return DirectiveRequest(
      directive: result[0]! as String,
      data: result[1] as String?,
    );
  }
}

/// 引擎事件消息（Native -> Dart）
class EngineEventMessage {
  EngineEventMessage({
    required this.type,
    this.text,
    this.audio,
  });

  /// 事件类型，如 "MESSAGE_TYPE_DIALOG_ASR_RESPONSE"
  String type;

  /// 文本数据
  String? text;

  /// 二进制音频数据
  Uint8List? audio;

  Object encode() {
    return <Object?>[
      type,
      text,
      audio,
    ];
  }

  static EngineEventMessage decode(Object result) {
    result as List<Object?>;
    return EngineEventMessage(
      type: result[0]! as String,
      text: result[1] as String?,
      audio: result[2] as Uint8List?,
    );
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is EngineConfigMessage) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is DirectiveRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is EngineEventMessage) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        return EngineConfigMessage.decode(readValue(buffer)!);
      case 130: 
        return DirectiveRequest.decode(readValue(buffer)!);
      case 131: 
        return EngineEventMessage.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DoubaoVoiceHostApi {
  /// Constructor for [DoubaoVoiceHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DoubaoVoiceHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// 准备环境（App 生命周期内仅一次）
  Future<bool> prepareEnvironment() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.prepareEnvironment$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as bool?)!;
    }
  }

  /// 创建引擎实例
  Future<void> createEngine() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.createEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 批量配置引擎参数
  Future<void> configure(EngineConfigMessage config) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.configure$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[config]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设置字符串参数
  Future<void> setOptionString(String key, String value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionString$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设置布尔参数
  Future<void> setOptionBool(String key, bool value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionBool$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 设置整数参数
  Future<void> setOptionInt(String key, int value) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionInt$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[key, value]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 初始化引擎，返回错误码（0 = 成功）
  Future<int> initEngine() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.initEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  /// 发送指令
  Future<void> sendDirective(DirectiveRequest request) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.sendDirective$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[request]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 传入 PCM 音频数据，返回错误码
  Future<int> feedAudio(Uint8List buffer) async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.feedAudio$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(<Object?>[buffer]) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else if (pigeonVar_replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (pigeonVar_replyList[0] as int?)!;
    }
  }

  /// 停止引擎（异步执行，避免回调线程死锁）
  Future<void> stopEngine() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.stopEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }

  /// 销毁引擎（异步执行）
  Future<void> destroyEngine() async {
    final String pigeonVar_channelName = 'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.destroyEngine$pigeonVar_messageChannelSuffix';
    final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final List<Object?>? pigeonVar_replyList =
        await pigeonVar_channel.send(null) as List<Object?>?;
    if (pigeonVar_replyList == null) {
      throw _createConnectionError(pigeonVar_channelName);
    } else if (pigeonVar_replyList.length > 1) {
      throw PlatformException(
        code: pigeonVar_replyList[0]! as String,
        message: pigeonVar_replyList[1] as String?,
        details: pigeonVar_replyList[2],
      );
    } else {
      return;
    }
  }
}

abstract class DoubaoVoiceFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// 引擎事件回调
  void onEngineEvent(EngineEventMessage event);

  static void setUp(DoubaoVoiceFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final BasicMessageChannel<Object?> pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceFlutterApi.onEngineEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceFlutterApi.onEngineEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final EngineEventMessage? arg_event = (args[0] as EngineEventMessage?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceFlutterApi.onEngineEvent was null, expected non-null EngineEventMessage.');
          try {
            api.onEngineEvent(arg_event!);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
