// Autogenerated from Pigeon (v22.7.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.volcengine.doubao_voice_engine

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  return if (exception is FlutterError) {
    listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

private fun createConnectionError(channelName: String): FlutterError {
  return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/**
 * 引擎配置消息（替代之前的 Map<String, dynamic>）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EngineConfigMessage (
  /** 鉴权 — 必需 */
  val appId: String,
  val appKey: String,
  val appToken: String,
  val resourceId: String,
  val uid: String,
  val dialogAddress: String,
  val dialogUri: String,
  /** 引擎基础 */
  val debugPath: String? = null,
  val logLevel: String,
  /** AEC 回声消除 */
  val enableAec: Boolean,
  val aecModelPath: String? = null,
  /** 录音机 */
  val recorderType: String,
  val recorderPath: String? = null,
  val enableRecorderAudioCallback: Boolean,
  /** 播放器 */
  val enablePlayer: Boolean,
  val enablePlayerAudioCallback: Boolean,
  val enableDecoderAudioCallback: Boolean,
  val playerPath: String? = null,
  /** 工作模式（null = 不设置，使用 SDK 默认值） */
  val dialogWorkMode: Long? = null,
  /** 重采样 */
  val enableResampler: Boolean,
  val customSampleRate: Long? = null,
  val customChannel: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineConfigMessage {
      val appId = pigeonVar_list[0] as String
      val appKey = pigeonVar_list[1] as String
      val appToken = pigeonVar_list[2] as String
      val resourceId = pigeonVar_list[3] as String
      val uid = pigeonVar_list[4] as String
      val dialogAddress = pigeonVar_list[5] as String
      val dialogUri = pigeonVar_list[6] as String
      val debugPath = pigeonVar_list[7] as String?
      val logLevel = pigeonVar_list[8] as String
      val enableAec = pigeonVar_list[9] as Boolean
      val aecModelPath = pigeonVar_list[10] as String?
      val recorderType = pigeonVar_list[11] as String
      val recorderPath = pigeonVar_list[12] as String?
      val enableRecorderAudioCallback = pigeonVar_list[13] as Boolean
      val enablePlayer = pigeonVar_list[14] as Boolean
      val enablePlayerAudioCallback = pigeonVar_list[15] as Boolean
      val enableDecoderAudioCallback = pigeonVar_list[16] as Boolean
      val playerPath = pigeonVar_list[17] as String?
      val dialogWorkMode = pigeonVar_list[18] as Long?
      val enableResampler = pigeonVar_list[19] as Boolean
      val customSampleRate = pigeonVar_list[20] as Long?
      val customChannel = pigeonVar_list[21] as Long?
      return EngineConfigMessage(appId, appKey, appToken, resourceId, uid, dialogAddress, dialogUri, debugPath, logLevel, enableAec, aecModelPath, recorderType, recorderPath, enableRecorderAudioCallback, enablePlayer, enablePlayerAudioCallback, enableDecoderAudioCallback, playerPath, dialogWorkMode, enableResampler, customSampleRate, customChannel)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      appId,
      appKey,
      appToken,
      resourceId,
      uid,
      dialogAddress,
      dialogUri,
      debugPath,
      logLevel,
      enableAec,
      aecModelPath,
      recorderType,
      recorderPath,
      enableRecorderAudioCallback,
      enablePlayer,
      enablePlayerAudioCallback,
      enableDecoderAudioCallback,
      playerPath,
      dialogWorkMode,
      enableResampler,
      customSampleRate,
      customChannel,
    )
  }
}

/**
 * 指令请求
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class DirectiveRequest (
  /** 指令名称，如 "DIRECTIVE_START_ENGINE" */
  val directive: String,
  /** 可选 JSON 参数 */
  val data: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DirectiveRequest {
      val directive = pigeonVar_list[0] as String
      val data = pigeonVar_list[1] as String?
      return DirectiveRequest(directive, data)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      directive,
      data,
    )
  }
}

/**
 * 引擎事件消息（Native -> Dart）
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class EngineEventMessage (
  /** 事件类型，如 "MESSAGE_TYPE_DIALOG_ASR_RESPONSE" */
  val type: String,
  /** 文本数据 */
  val text: String? = null,
  /** 二进制音频数据 */
  val audio: ByteArray? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EngineEventMessage {
      val type = pigeonVar_list[0] as String
      val text = pigeonVar_list[1] as String?
      val audio = pigeonVar_list[2] as ByteArray?
      return EngineEventMessage(type, text, audio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      text,
      audio,
    )
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineConfigMessage.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DirectiveRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EngineEventMessage.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is EngineConfigMessage -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is DirectiveRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is EngineEventMessage -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DoubaoVoiceHostApi {
  /** 准备环境（App 生命周期内仅一次） */
  fun prepareEnvironment(): Boolean
  /** 创建引擎实例 */
  fun createEngine()
  /** 批量配置引擎参数 */
  fun configure(config: EngineConfigMessage)
  /** 设置字符串参数 */
  fun setOptionString(key: String, value: String)
  /** 设置布尔参数 */
  fun setOptionBool(key: String, value: Boolean)
  /** 设置整数参数 */
  fun setOptionInt(key: String, value: Long)
  /** 初始化引擎，返回错误码（0 = 成功） */
  fun initEngine(): Long
  /** 发送指令 */
  fun sendDirective(request: DirectiveRequest)
  /** 传入 PCM 音频数据，返回错误码 */
  fun feedAudio(buffer: ByteArray): Long
  /** 停止引擎（异步执行，避免回调线程死锁） */
  fun stopEngine(callback: (Result<Unit>) -> Unit)
  /** 销毁引擎（异步执行） */
  fun destroyEngine(callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by DoubaoVoiceHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `DoubaoVoiceHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DoubaoVoiceHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.prepareEnvironment$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.prepareEnvironment())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.createEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              api.createEngine()
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.configure$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val configArg = args[0] as EngineConfigMessage
            val wrapped: List<Any?> = try {
              api.configure(configArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionString$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as String
            val wrapped: List<Any?> = try {
              api.setOptionString(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionBool$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as Boolean
            val wrapped: List<Any?> = try {
              api.setOptionBool(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.setOptionInt$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val keyArg = args[0] as String
            val valueArg = args[1] as Long
            val wrapped: List<Any?> = try {
              api.setOptionInt(keyArg, valueArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.initEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.initEngine())
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.sendDirective$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as DirectiveRequest
            val wrapped: List<Any?> = try {
              api.sendDirective(requestArg)
              listOf(null)
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.feedAudio$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val bufferArg = args[0] as ByteArray
            val wrapped: List<Any?> = try {
              listOf(api.feedAudio(bufferArg))
            } catch (exception: Throwable) {
              wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.stopEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.stopEngine{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceHostApi.destroyEngine$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.destroyEngine{ result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DoubaoVoiceFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DoubaoVoiceFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** 引擎事件回调 */
  fun onEngineEvent(eventArg: EngineEventMessage, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.doubao_voice_engine.DoubaoVoiceFlutterApi.onEngineEvent$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(eventArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(createConnectionError(channelName)))
      } 
    }
  }
}
